### PR TITLE
fix(ci): publisher concurrency

### PR DESCRIPTION
**Pull request by developStorm**
I did some testing on my fork and it should solve the problem now.

(Tested by tagging 9 issues in the same time, the new approach handled them correctly: [commit](https://github.com/developStorm/appleprivacyletter/commit/185d502ccb9f4df9dbd2062a39f58183b5d2c6d0), [action run](https://github.com/developStorm/appleprivacyletter/runs/3269113312))

This new approach also increases robustness, so that even if the worst-case workflow run fails, any previously unprocessed issues will be reprocessed the next time any issue get labeled.

### CODE REVIEW

**Comment by nadimkobeissi** [comment]
Labeling issues now doesn't do anything at all.

**Comment by nadimkobeissi** [comment]
Nevermind, it worked!

**Comment by developStorm** [comment]
I guess it's just delayed a while as GitHub sorting out the concurrency priority haha

**Comment by nadimkobeissi** [comment]
Sorry, this really doesn't work and is unreliable. I'm removing it. You're welcome to try pull requesting code again once you're sure it works reliably.

**Comment by developStorm** [comment]
Would you think an asynchronous merge be acceptable? I can change it to run in every 10 min or so to avoid concurrency problems

**Pull request merged**
