### PR TITLE
New signature automated with GitHub Action

### PR DESCRIPTION
**Pull request by developStorm**
These changes create a JSON snippet for each new issue labeled by signature (see [example](https://github.com/developStorm/appleprivacyletter/issues/9)), and append the snippet to the script.js once the issue get tagged as signature-approved.

### CODE REVIEW

**Comment by nadimkobeissi** [comment]
Thanks, I'm going to add this manually to prevent a merge conflict.

**Comment by nadimkobeissi** [comment]
@developStorm We have a problem: if I label a signature as approved while the action is already running, it doesn't detect the newly labeled signature. Also if I label multiple signatures at once, it only processes one of them.

**Comment by developStorm** [comment]
@nadimkobeissi I'm aware about that. I used a experimental flag [concurrency](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) to prevent mutiple action run in parallel (and then cause commit conflict), but it looks like only one pending job is allowed with that flag. I'll see what I can do.

**Comment by developStorm** [comment]
Update: concurrency flag cannot do what we want as for now (still [in discussion](https://github.community/t/how-to-limit-concurrent-workflow-runs/16844/50)). But I found https://github.com/shogo82148/actions-mutex provided a compelling solution. I'll try to migrate to use that.

**Pull request closed without merging**
